////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Runtime;
using BDSM.StandardLibrary;
using Beta.DI;

namespace Beta.BDSM;

public abstract class BDSMEventHandler
{
    protected abstract void OnDefineActor(object? sender, DefineActorEventArgs e);
    protected abstract void OnDefineScene(object? sender, DefineSceneEventArgs e);
    protected abstract void OnSetScene(object? sender, SetSceneEventArgs e);
    protected abstract void OnSetPlayer(object? sender, SetPlayerEventArgs e);
    protected abstract void OnActorSay(object? sender, ActorSayEventArgs e);
    protected abstract void OnActorTalkTo(object? sender, ActorTalkToEventArgs e);
    protected abstract void OnItemPickup(object? sender, ItemPickupEventArgs e);
    protected abstract void OnPlayerItemRemove(object? sender, PlayerItemRemoveEventArgs e);
    protected abstract void OnPlayerItemAdd(object? sender, PlayerItemAddEventArgs e);
    protected abstract void OnActorMove(object? sender, ActorMoveEventArgs e);
    protected abstract void OnSetPos(object? sender, SetPosEventArgs e);
    protected abstract void OnActorPut(object? sender, ActorPutEventArgs e);
    protected abstract void OnPlayAnimation(object? sender, PlayAnimationEventArgs e);
    protected abstract void OnSceneAdd(object? sender, SceneAddEventArgs e);
    protected abstract void OnSceneRemove(object? sender, SceneRemoveEventArgs e);
    protected abstract void OnWait(object? sender, WaitEventArgs e);
    protected abstract void OnActorInterrupt(object? sender, ActorInterruptEventArgs e);
    protected abstract void OnCamZoom(object? sender, CamZoomEventArgs e);
    protected abstract void OnSetCamPos(object? sender, SetCamPosEventArgs e);
    protected abstract void OnCloseup(object? sender, CloseupEventArgs e);
    protected abstract void OnPlaySong(object? sender, PlaySongEventArgs e);
    protected abstract void OnPlaySound(object? sender, PlaySoundEventArgs e);
    protected abstract void OnStopSong(object? sender, StopSongEventArgs e);
    protected abstract void OnPlayVideo(object? sender, PlayVideoEventArgs e);
    protected abstract void OnRequestMainMenu(object? sender, RequestMainMenuEventArgs e);
    protected abstract void OnRequestTutorial(object? sender, RequestTutorialEventArgs e);
    protected abstract void OnEndGame(object? sender, EndGameEventArgs e);
    protected abstract void OnFadeIn(object? sender, FadeInEventArgs e);
    protected abstract void OnFadeOut(object? sender, FadeOutEventArgs e);
    protected abstract void OnCinematicStart(object? sender, CinematicStartEventArgs e);
    protected abstract void OnCinematicEnd(object? sender, CinematicEndEventArgs e);
    protected abstract void OnDetachCam(object? sender, DetachCamEventArgs e);
    protected abstract void OnRequestStatePlaying(object? sender, RequestStatePlayingEventArgs e);
    protected abstract void OnSetState(object? sender, SetStateEventArgs e);
    protected abstract void OnInterrupt(object? sender, InterruptEventArgs e);
    protected abstract void OnActorSetIsShowChildren(object? sender, ActorSetIsShowChildrenEventArgs e);
    protected abstract void OnNarrate(object? sender, NarrateEventArgs e);
    protected abstract void OnMoveCamTo(object? sender, MoveCamToEventArgs e);
    protected abstract void OnSetCostume(object? sender, SetCostumeEventArgs e);
    protected abstract void OnAutosave(object? sender, AutosaveEventArgs e);
    protected abstract void OnFreespeech(object? sender, FreespeechEventArgs e);
    protected abstract void OnRequestStartMenu(object? sender, RequestStartMenuEventArgs e);
    protected abstract void OnTip(object? sender, TipEventArgs e);
    protected abstract void OnNotify(object? sender, NotifyEventArgs e);
    protected abstract void OnClearInventory(object? sender, ClearInventoryEventArgs e);


    protected readonly Driver _bdsmDriver;

    public BDSMEventHandler()
    {
        _bdsmDriver = DependencyContainer.Instance.Get<Driver>();
    }

    protected void Register()
    {
        _bdsmDriver.Interpreter.EventHandlers.OnDefineActor += OnDefineActor;
        _bdsmDriver.Interpreter.EventHandlers.OnDefineScene += OnDefineScene;
        _bdsmDriver.Interpreter.EventHandlers.OnSetScene += OnSetScene;
        _bdsmDriver.Interpreter.EventHandlers.OnSetPlayer += OnSetPlayer;
        _bdsmDriver.Interpreter.EventHandlers.OnActorSay += OnActorSay;
        _bdsmDriver.Interpreter.EventHandlers.OnActorTalkTo += OnActorTalkTo;
        _bdsmDriver.Interpreter.EventHandlers.OnItemPickup += OnItemPickup;
        _bdsmDriver.Interpreter.EventHandlers.OnPlayerItemRemove += OnPlayerItemRemove;
        _bdsmDriver.Interpreter.EventHandlers.OnPlayerItemAdd += OnPlayerItemAdd;
        _bdsmDriver.Interpreter.EventHandlers.OnActorMove += OnActorMove;
        _bdsmDriver.Interpreter.EventHandlers.OnSetPos += OnSetPos;
        _bdsmDriver.Interpreter.EventHandlers.OnActorPut += OnActorPut;
        _bdsmDriver.Interpreter.EventHandlers.OnPlayAnimation += OnPlayAnimation;
        _bdsmDriver.Interpreter.EventHandlers.OnSceneAdd += OnSceneAdd;
        _bdsmDriver.Interpreter.EventHandlers.OnSceneRemove += OnSceneRemove;
        _bdsmDriver.Interpreter.EventHandlers.OnWait += OnWait;
        _bdsmDriver.Interpreter.EventHandlers.OnActorInterrupt += OnActorInterrupt;
        _bdsmDriver.Interpreter.EventHandlers.OnCamZoom += OnCamZoom;
        _bdsmDriver.Interpreter.EventHandlers.OnSetCamPos += OnSetCamPos;
        _bdsmDriver.Interpreter.EventHandlers.OnCloseup += OnCloseup;
        _bdsmDriver.Interpreter.EventHandlers.OnPlaySong += OnPlaySong;
        _bdsmDriver.Interpreter.EventHandlers.OnPlaySound += OnPlaySound;
        _bdsmDriver.Interpreter.EventHandlers.OnStopSong += OnStopSong;
        _bdsmDriver.Interpreter.EventHandlers.OnPlayVideo += OnPlayVideo;
        _bdsmDriver.Interpreter.EventHandlers.OnRequestMainMenu += OnRequestMainMenu;
        _bdsmDriver.Interpreter.EventHandlers.OnRequestTutorial += OnRequestTutorial;
        _bdsmDriver.Interpreter.EventHandlers.OnEndGame += OnEndGame;
        _bdsmDriver.Interpreter.EventHandlers.OnFadeIn += OnFadeIn;
        _bdsmDriver.Interpreter.EventHandlers.OnFadeOut += OnFadeOut;
        _bdsmDriver.Interpreter.EventHandlers.OnCinematicStart += OnCinematicStart;
        _bdsmDriver.Interpreter.EventHandlers.OnCinematicEnd += OnCinematicEnd;
        _bdsmDriver.Interpreter.EventHandlers.OnDetachCam += OnDetachCam;
        _bdsmDriver.Interpreter.EventHandlers.OnRequestStatePlaying += OnRequestStatePlaying;
        _bdsmDriver.Interpreter.EventHandlers.OnSetState += OnSetState;
        _bdsmDriver.Interpreter.EventHandlers.OnInterrupt += OnInterrupt;
        _bdsmDriver.Interpreter.EventHandlers.OnActorSetIsShowChildren += OnActorSetIsShowChildren;
        _bdsmDriver.Interpreter.EventHandlers.OnNarrate += OnNarrate;
        _bdsmDriver.Interpreter.EventHandlers.OnMoveCamTo += OnMoveCamTo;
        _bdsmDriver.Interpreter.EventHandlers.OnSetCostume += OnSetCostume;
        _bdsmDriver.Interpreter.EventHandlers.OnAutosave += OnAutosave;
        _bdsmDriver.Interpreter.EventHandlers.OnFreespeech += OnFreespeech;
        _bdsmDriver.Interpreter.EventHandlers.OnRequestStartMenu += OnRequestStartMenu;
        _bdsmDriver.Interpreter.EventHandlers.OnTip += OnTip;
        _bdsmDriver.Interpreter.EventHandlers.OnNotify += OnNotify;
        _bdsmDriver.Interpreter.EventHandlers.OnClearInventory += OnClearInventory;

    }
}

