// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FieldSaveData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BDSM.Runtime.SaveGames {

  /// <summary>Holder for reflection information generated from FieldSaveData.proto</summary>
  public static partial class FieldSaveDataReflection {

    #region Descriptor
    /// <summary>File descriptor for FieldSaveData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FieldSaveDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNGaWVsZFNhdmVEYXRhLnByb3RvEgRCZXRhIt8CCg1GaWVsZFNhdmVEYXRh",
            "EjsKDHN0cmluZ0ZpZWxkcxgBIAMoCzIlLkJldGEuRmllbGRTYXZlRGF0YS5T",
            "dHJpbmdGaWVsZHNFbnRyeRI7Cgxkb3VibGVGaWVsZHMYAiADKAsyJS5CZXRh",
            "LkZpZWxkU2F2ZURhdGEuRG91YmxlRmllbGRzRW50cnkSNwoKYm9vbEZpZWxk",
            "cxgDIAMoCzIjLkJldGEuRmllbGRTYXZlRGF0YS5Cb29sRmllbGRzRW50cnka",
            "MwoRU3RyaW5nRmllbGRzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIg",
            "ASgJOgI4ARozChFEb3VibGVGaWVsZHNFbnRyeRILCgNrZXkYASABKAkSDQoF",
            "dmFsdWUYAiABKAE6AjgBGjEKD0Jvb2xGaWVsZHNFbnRyeRILCgNrZXkYASAB",
            "KAkSDQoFdmFsdWUYAiABKAg6AjgBQhmqAhZCRFNNLlJ1bnRpbWUuU2F2ZUdh",
            "bWVzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BDSM.Runtime.SaveGames.FieldSaveData), global::BDSM.Runtime.SaveGames.FieldSaveData.Parser, new[]{ "StringFields", "DoubleFields", "BoolFields" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FieldSaveData : pb::IMessage<FieldSaveData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FieldSaveData> _parser = new pb::MessageParser<FieldSaveData>(() => new FieldSaveData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FieldSaveData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BDSM.Runtime.SaveGames.FieldSaveDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FieldSaveData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FieldSaveData(FieldSaveData other) : this() {
      stringFields_ = other.stringFields_.Clone();
      doubleFields_ = other.doubleFields_.Clone();
      boolFields_ = other.boolFields_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FieldSaveData Clone() {
      return new FieldSaveData(this);
    }

    /// <summary>Field number for the "stringFields" field.</summary>
    public const int StringFieldsFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_stringFields_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 10);
    private readonly pbc::MapField<string, string> stringFields_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> StringFields {
      get { return stringFields_; }
    }

    /// <summary>Field number for the "doubleFields" field.</summary>
    public const int DoubleFieldsFieldNumber = 2;
    private static readonly pbc::MapField<string, double>.Codec _map_doubleFields_codec
        = new pbc::MapField<string, double>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForDouble(17, 0D), 18);
    private readonly pbc::MapField<string, double> doubleFields_ = new pbc::MapField<string, double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, double> DoubleFields {
      get { return doubleFields_; }
    }

    /// <summary>Field number for the "boolFields" field.</summary>
    public const int BoolFieldsFieldNumber = 3;
    private static readonly pbc::MapField<string, bool>.Codec _map_boolFields_codec
        = new pbc::MapField<string, bool>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBool(16, false), 26);
    private readonly pbc::MapField<string, bool> boolFields_ = new pbc::MapField<string, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, bool> BoolFields {
      get { return boolFields_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FieldSaveData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FieldSaveData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!StringFields.Equals(other.StringFields)) return false;
      if (!DoubleFields.Equals(other.DoubleFields)) return false;
      if (!BoolFields.Equals(other.BoolFields)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= StringFields.GetHashCode();
      hash ^= DoubleFields.GetHashCode();
      hash ^= BoolFields.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      stringFields_.WriteTo(output, _map_stringFields_codec);
      doubleFields_.WriteTo(output, _map_doubleFields_codec);
      boolFields_.WriteTo(output, _map_boolFields_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      stringFields_.WriteTo(ref output, _map_stringFields_codec);
      doubleFields_.WriteTo(ref output, _map_doubleFields_codec);
      boolFields_.WriteTo(ref output, _map_boolFields_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += stringFields_.CalculateSize(_map_stringFields_codec);
      size += doubleFields_.CalculateSize(_map_doubleFields_codec);
      size += boolFields_.CalculateSize(_map_boolFields_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FieldSaveData other) {
      if (other == null) {
        return;
      }
      stringFields_.MergeFrom(other.stringFields_);
      doubleFields_.MergeFrom(other.doubleFields_);
      boolFields_.MergeFrom(other.boolFields_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            stringFields_.AddEntriesFrom(input, _map_stringFields_codec);
            break;
          }
          case 18: {
            doubleFields_.AddEntriesFrom(input, _map_doubleFields_codec);
            break;
          }
          case 26: {
            boolFields_.AddEntriesFrom(input, _map_boolFields_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            stringFields_.AddEntriesFrom(ref input, _map_stringFields_codec);
            break;
          }
          case 18: {
            doubleFields_.AddEntriesFrom(ref input, _map_doubleFields_codec);
            break;
          }
          case 26: {
            boolFields_.AddEntriesFrom(ref input, _map_boolFields_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
