////////////////////////////////////////////////////////////
//
// ! Generated by make-ast.py.
// ! Changes to this file will be lost during regeneration.
//
////////////////////////////////////////////////////////////


#nullable disable

using BDSM.Tokens;
using BDSM.ExecutionContexts;
using System.Collections.Generic;

namespace BDSM.Language;

public interface ExpressionVisitor<T>
{
    T VisitAssignExpression(AssignExpression assign, ExecutionContext context);
    T VisitBinaryExpression(BinaryExpression binary, ExecutionContext context);
    T VisitGroupingExpression(GroupingExpression grouping, ExecutionContext context);
    T VisitLiteralExpression(LiteralExpression literal, ExecutionContext context);
    T VisitLogicalExpression(LogicalExpression logical, ExecutionContext context);
    T VisitSetExpression(SetExpression set, ExecutionContext context);
    T VisitUnaryExpression(UnaryExpression unary, ExecutionContext context);
    T VisitCallExpression(CallExpression call, ExecutionContext context);
    T VisitGetExpression(GetExpression get, ExecutionContext context);
    T VisitTupleExpression(TupleExpression tuple, ExecutionContext context);
    T VisitVariableExpression(VariableExpression variable, ExecutionContext context);
}

public abstract class Expression
{
    public abstract T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context);
}

public class AssignExpression : Expression
{
    public AssignExpression(Token name, Expression val)
    {
        this.name = name;
        this.val = val;
    }

    public Token name;
    public Expression val;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitAssignExpression(this, context);
    }
}

public class BinaryExpression : Expression
{
    public BinaryExpression(Expression left, Token op, Expression right)
    {
        this.left = left;
        this.op = op;
        this.right = right;
    }

    public Expression left;
    public Token op;
    public Expression right;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitBinaryExpression(this, context);
    }
}

public class GroupingExpression : Expression
{
    public GroupingExpression(Expression expr)
    {
        this.expr = expr;
    }

    public Expression expr;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitGroupingExpression(this, context);
    }
}

public class LiteralExpression : Expression
{
    public LiteralExpression(object val)
    {
        this.val = val;
    }

    public object val;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitLiteralExpression(this, context);
    }
}

public class LogicalExpression : Expression
{
    public LogicalExpression(Expression left, Token op, Expression right)
    {
        this.left = left;
        this.op = op;
        this.right = right;
    }

    public Expression left;
    public Token op;
    public Expression right;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitLogicalExpression(this, context);
    }
}

public class SetExpression : Expression
{
    public SetExpression(Expression obj, Token name, Expression val)
    {
        this.obj = obj;
        this.name = name;
        this.val = val;
    }

    public Expression obj;
    public Token name;
    public Expression val;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitSetExpression(this, context);
    }
}

public class UnaryExpression : Expression
{
    public UnaryExpression(Token op, Expression expr)
    {
        this.op = op;
        this.expr = expr;
    }

    public Token op;
    public Expression expr;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitUnaryExpression(this, context);
    }
}

public class CallExpression : Expression
{
    public CallExpression(Expression callee, Token paren, List<Expression> arguments)
    {
        this.callee = callee;
        this.paren = paren;
        this.arguments = arguments;
    }

    public Expression callee;
    public Token paren;
    public List<Expression> arguments;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitCallExpression(this, context);
    }
}

public class GetExpression : Expression
{
    public GetExpression(Expression instance, Token name)
    {
        this.instance = instance;
        this.name = name;
    }

    public Expression instance;
    public Token name;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitGetExpression(this, context);
    }
}

public class TupleExpression : Expression
{
    public TupleExpression(Token paren, List<Expression> members)
    {
        this.paren = paren;
        this.members = members;
    }

    public Token paren;
    public List<Expression> members;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitTupleExpression(this, context);
    }
}

public class VariableExpression : Expression
{
    public VariableExpression(Token name)
    {
        this.name = name;
    }

    public Token name;

    public override T Accept<T>(ExpressionVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitVariableExpression(this, context);
    }
}

