////////////////////////////////////////////////////////////
//
// ! Generated by make-ast.py.
// ! Changes to this file will be lost during regeneration.
//
////////////////////////////////////////////////////////////


#nullable disable

using BDSM.Tokens;
using BDSM.ExecutionContexts;
using System.Collections.Generic;

namespace BDSM.Language;

public interface StatementVisitor<T>
{
    T VisitImportStatement(ImportStatement import, ExecutionContext context);
    T VisitBlockStatement(BlockStatement block, ExecutionContext context);
    T VisitSceneStatement(SceneStatement scene, ExecutionContext context);
    T VisitRegionStatement(RegionStatement region, ExecutionContext context);
    T VisitPropStatement(PropStatement prop, ExecutionContext context);
    T VisitActorStatement(ActorStatement actor, ExecutionContext context);
    T VisitVerbStatement(VerbStatement verb, ExecutionContext context);
    T VisitExpressionStatement(ExpressionStatement expression, ExecutionContext context);
    T VisitFunctionStatement(FunctionStatement function, ExecutionContext context);
    T VisitIfsStatement(IfsStatement ifs, ExecutionContext context);
    T VisitPrintStatement(PrintStatement print, ExecutionContext context);
    T VisitReturnsStatement(ReturnsStatement returns, ExecutionContext context);
    T VisitAsyncStatement(AsyncStatement async, ExecutionContext context);
    T VisitVarStatement(VarStatement var, ExecutionContext context);
    T VisitWhilesStatement(WhilesStatement whiles, ExecutionContext context);
}

public abstract class Statement
{
    public abstract T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context);
}

public class ImportStatement : Statement
{
    public ImportStatement(Token what)
    {
        this.what = what;
    }

    public Token what;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitImportStatement(this, context);
    }
}

public class BlockStatement : Statement
{
    public BlockStatement(List<Statement> statements)
    {
        this.statements = statements;
    }

    public List<Statement> statements;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitBlockStatement(this, context);
    }
}

public class SceneStatement : Statement
{
    public SceneStatement(Token declName, List<VarStatement> vars, List<FunctionStatement> functions, List<RegionStatement> regions, List<PropStatement> props)
    {
        this.declName = declName;
        this.vars = vars;
        this.functions = functions;
        this.regions = regions;
        this.props = props;
    }

    public Token declName;
    public List<VarStatement> vars;
    public List<FunctionStatement> functions;
    public List<RegionStatement> regions;
    public List<PropStatement> props;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitSceneStatement(this, context);
    }
}

public class RegionStatement : Statement
{
    public RegionStatement(Token declName, List<FunctionStatement> functions)
    {
        this.declName = declName;
        this.functions = functions;
    }

    public Token declName;
    public List<FunctionStatement> functions;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitRegionStatement(this, context);
    }
}

public class PropStatement : Statement
{
    public PropStatement(Token declName, Token name, List<VerbStatement> verbs)
    {
        this.declName = declName;
        this.name = name;
        this.verbs = verbs;
    }

    public Token declName;
    public Token name;
    public List<VerbStatement> verbs;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitPropStatement(this, context);
    }
}

public class ActorStatement : Statement
{
    public ActorStatement(Token declName, List<Statement> verbs, List<VarStatement> vars, List<FunctionStatement> functions)
    {
        this.declName = declName;
        this.verbs = verbs;
        this.vars = vars;
        this.functions = functions;
    }

    public Token declName;
    public List<Statement> verbs;
    public List<VarStatement> vars;
    public List<FunctionStatement> functions;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitActorStatement(this, context);
    }
}

public class VerbStatement : Statement
{
    public VerbStatement(Token name, Token item, List<Statement> statements)
    {
        this.name = name;
        this.item = item;
        this.statements = statements;
    }

    public Token name;
    public Token item;
    public List<Statement> statements;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitVerbStatement(this, context);
    }
}

public class ExpressionStatement : Statement
{
    public ExpressionStatement(Expression expr)
    {
        this.expr = expr;
    }

    public Expression expr;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitExpressionStatement(this, context);
    }
}

public class FunctionStatement : Statement
{
    public FunctionStatement(Token name, List<Token> parameters, List<Statement> body)
    {
        this.name = name;
        this.parameters = parameters;
        this.body = body;
    }

    public Token name;
    public List<Token> parameters;
    public List<Statement> body;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitFunctionStatement(this, context);
    }
}

public class IfsStatement : Statement
{
    public IfsStatement(Expression condition, Statement thenBranch, Statement elseBranch)
    {
        this.condition = condition;
        this.thenBranch = thenBranch;
        this.elseBranch = elseBranch;
    }

    public Expression condition;
    public Statement thenBranch;
    public Statement elseBranch;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitIfsStatement(this, context);
    }
}

public class PrintStatement : Statement
{
    public PrintStatement(Expression expr)
    {
        this.expr = expr;
    }

    public Expression expr;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitPrintStatement(this, context);
    }
}

public class ReturnsStatement : Statement
{
    public ReturnsStatement(Token keyword, Expression value)
    {
        this.keyword = keyword;
        this.value = value;
    }

    public Token keyword;
    public Expression value;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitReturnsStatement(this, context);
    }
}

public class AsyncStatement : Statement
{
    public AsyncStatement(Statement body, Statement then)
    {
        this.body = body;
        this.then = then;
    }

    public Statement body;
    public Statement then;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitAsyncStatement(this, context);
    }
}

public class VarStatement : Statement
{
    public VarStatement(Token name, Expression initializer)
    {
        this.name = name;
        this.initializer = initializer;
    }

    public Token name;
    public Expression initializer;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitVarStatement(this, context);
    }
}

public class WhilesStatement : Statement
{
    public WhilesStatement(Expression condition, Statement body)
    {
        this.condition = condition;
        this.body = body;
    }

    public Expression condition;
    public Statement body;

    public override T Accept<T>(StatementVisitor<T> visitor, ExecutionContext context)
    {
        return visitor.VisitWhilesStatement(this, context);
    }
}
