namespace Beta.InputMapping;

public enum GameInputType
{
    OverlayCancel,
    MainMenuConfirm,
    ToggleMainMenu,
    DoLook,
    DoTalk,
    DoInteract,
    DoPickup,
    ToggleInventory,
    DialogueOptionPrev,
    DialogueOptionNext,
    DialogueOptionSubmit,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    ShowHotspots,
    ToggleHelp,
    ToggleDebug,
    LogMore,
    LogLess,
    CursorPositionChanged,
    CursorMainAction,
    CursorMainActionAtPosition,
    CursorDragged,
    NumberSelected,
    CameraLeft,
    CameraRight,
    CursorSecondaryAction,
    DoWalk,
    Cancel,

    NextTutorial,
    PrevTutorial,
    ReloadTutorial,
}
