////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Instances;
using BDSM.Runtime;
using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class ActorSetIsShowChildrenMethod : ICallable
{
    public int Arity() => 1;

    private readonly BDSMActor _caller;

    public ActorSetIsShowChildrenMethod(BDSMActor caller)
    {
        _caller = caller;
    }

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnActorSetIsShowChildren(this, new ActorSetIsShowChildrenEventArgs(context, _caller, (bool) arguments[0]));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"{_caller.DeclName}.actorsetisshowchildren() expects args:(bool) .");
        }
    }
}