////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

using BDSM.Events;
using BDSM.ExecutionContexts;
using BDSM.Instances;

namespace BDSM.StandardLibrary;

public class ActorSetIsShowChildrenEventArgs : BDSMEventArgs
{
    public BDSMActor Actor { get; set; }
    public bool IsShowChildren { get; set; }

    public ActorSetIsShowChildrenEventArgs(ExecutionContext context, BDSMActor who, bool isShowChildren) : base(context)
    {
        Actor = who;
        IsShowChildren = isShowChildren;
    }
}