////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

using BDSM.Events;
using BDSM.ExecutionContexts;

namespace BDSM.StandardLibrary;

public class AutosaveEventArgs : BDSMEventArgs
{
    public AutosaveEventArgs(ExecutionContext context) : base(context)
    {

    }
}
