////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Events;
using BDSM.ExecutionContexts;
using BDSM.Instances;

#nullable disable

namespace BDSM.StandardLibrary;

public class ClearInventoryEventArgs : BDSMEventArgs
{
    public BDSMActor Who { get; set; }

    public ClearInventoryEventArgs(ExecutionContext context, BDSMActor who) : base(context)
    {
        Who = who;
    }
}
