////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Instances;
using BDSM.Runtime;
using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class ClearInventoryMethod : ICallable
{
    public int Arity() => 0;

    private BDSMActor _caller;

    public ClearInventoryMethod(BDSMActor caller)
    {
        _caller = caller;
    }

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnClearInventory(this, new ClearInventoryEventArgs(context, _caller));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"{_caller.DeclName}.clearinventory() expects args:.");
        }
    }
}

