using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Runtime;
////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class FreespeechFunction : ICallable
{
    public int Arity() => 5;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnFreespeech(this, new FreespeechEventArgs(context, (string) arguments[0], (string)arguments[1], (string) arguments[2], (int)(double)arguments[3], (int)(double)arguments[4]));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"freespeech() expects args: (text:string) (actorName:string) (color:string) (x:int) (y:int).");
        }
    }
}