using BDSM.Events;
using BDSM.ExecutionContexts;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class FreespeechEventArgs : BDSMEventArgs
{
    public int X { get; set; }
    public int Y { get; set; }
    public string Text { get; set; }
    public string ActorName { get; set; }
    public string Color { get; set; }

    public FreespeechEventArgs(ExecutionContext context, string text, string actorName, string color, int x, int y) : base(context)
    {
        X = x;
        Y = y;
        ActorName = actorName;
        Text = text;
        Color = color;
    }
}