using BDSM.Events;
using BDSM.ExecutionContexts;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class InterruptEventArgs : BDSMEventArgs
{
    public bool InterruptAsync { get; }

    public InterruptEventArgs(ExecutionContext context, bool interruptAsync) : base(context)
    {
        InterruptAsync = interruptAsync;
    }
}