using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Runtime;
////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class InterruptFunction : ICallable
{
    public int Arity() => 1;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnInterrupt(this, new InterruptEventArgs(context, (bool)arguments[0]));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"interrupt() expects args: bool");
        }
    }
}