using BDSM.Events;
using BDSM.ExecutionContexts;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class MoveCamToEventArgs : BDSMEventArgs
{
    
    public int X { get; set; }
    public int Y { get; set; }
    public int Speed { get; set; }

    public MoveCamToEventArgs(ExecutionContext context, int x, int y, int speed) : base(context)
    {
        
        X = x;
        Y = y;
        Speed = speed;
    }
}
