using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Runtime;
////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class MoveCamToFunction : ICallable
{
    public int Arity() => 3;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnMoveCamTo(this, new MoveCamToEventArgs(context, (int)((double)arguments[0]), (int)((double)arguments[1]), (int)((double)arguments[2])));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"movecamto() expects args:(int) (int) (int) .");
        }
    }
}
