using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Runtime;
////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class NarrateFunction : ICallable
{
    public int Arity() => 1;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnNarrate(this, new NarrateEventArgs(context, (string) arguments[0]));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"narrate() expects args:(string) .");
        }
    }
}
