using BDSM.Events;
using BDSM.ExecutionContexts;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class NarrateEventArgs : BDSMEventArgs
{
    
    public string Text { get; set; }

    public NarrateEventArgs(ExecutionContext context, string text) : base(context)
    {
        
        Text = text;
    }
}
