////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Runtime;
using BDSM.Functions;
using BDSM.ExecutionContexts;
using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class NotifyFunction : ICallable
{
    public int Arity() => 2;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnNotify(this, new NotifyEventArgs(context, (int)((double)arguments[0]), (string) arguments[1]));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"notify() expects args:(int) (string) .");
        }
    }
}

