////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Events;
using BDSM.ExecutionContexts;

#nullable disable

namespace BDSM.StandardLibrary;

public class NotifyEventArgs : BDSMEventArgs
{
    public int DurationSeconds { get; set; }
    public string Text { get; set; }

    public NotifyEventArgs(ExecutionContext context, int durationSeconds, string text) : base(context)
    {

        DurationSeconds = durationSeconds;
        Text = text;
    }
}
