////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Events;
using BDSM.ExecutionContexts;

#nullable disable

namespace BDSM.StandardLibrary;

public class RequestStartMenuEventArgs : BDSMEventArgs
{
    

    public RequestStartMenuEventArgs(ExecutionContext context) : base(context)
    {
        
    }
}

