////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Runtime;
using BDSM.Functions;
using BDSM.ExecutionContexts;
using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class RequestStartMenuFunction : ICallable
{
    public int Arity() => 0;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnRequestStartMenu(this, new RequestStartMenuEventArgs(context));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"requeststartmenu() expects args:.");
        }
    }
}

