using BDSM.Events;
using BDSM.ExecutionContexts;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class RequestStatePlayingEventArgs : BDSMEventArgs
{
    

    public RequestStatePlayingEventArgs(ExecutionContext context) : base(context)
    {
        
    }
}
