using BDSM.Events;
using BDSM.ExecutionContexts;
using BDSM.Instances;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class SetCostumeEventArgs : BDSMEventArgs
{
    public string Name { get; set; }
    public BDSMActor Actor { get; set; }

    public SetCostumeEventArgs(ExecutionContext context, BDSMActor actor, string name) : base(context)
    {
        Actor = actor;
        Name = name;
    }
}