using BDSM.Events;
using BDSM.ExecutionContexts;
using BDSM.Instances;

////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

#nullable disable

namespace BDSM.StandardLibrary;

public class SetStateEventArgs : BDSMEventArgs
{    
    public BDSMActor Actor { get; set; }
    public string State { get; set; }

    public SetStateEventArgs(ExecutionContext context, BDSMActor actor, string state) : base(context)
    {
        Actor = actor;
        State = state;
    }
}