using BDSM.Instances;
using BDSM.ExecutionContexts;
using BDSM.Functions;
using BDSM.Runtime;
////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class SetStateMethod : ICallable
{
    public int Arity() => 1;

    private BDSMActor _caller;

    public SetStateMethod(BDSMActor caller)
    {
        _caller = caller;
    }

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnSetState(this, new SetStateEventArgs(context, _caller, (string) arguments[0]));
            _caller.State = (string)arguments[0];
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"{_caller.DeclName}.setstate() expects args:(string) .");
        }
    }
}