////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Events;
using BDSM.ExecutionContexts;

#nullable disable

namespace BDSM.StandardLibrary;

public class TipEventArgs : BDSMEventArgs
{
    
    public int DurationSeconds { get; set; }
    public string Id { get; set; }
    public string Text { get; set; }

    public TipEventArgs(ExecutionContext context, int durationSeconds, string id, string text) : base(context)
    {
        
        DurationSeconds = durationSeconds;
        Id = id;
        Text = text;
    }
}

