////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.Runtime;
using BDSM.Functions;
using BDSM.ExecutionContexts;
using System;
using System.Collections.Generic;

#nullable disable

namespace BDSM.StandardLibrary;

public class TipFunction : ICallable
{
    public int Arity() => 3;

    public object Call(Interpreter interpreter, List<object> arguments, ExecutionContext context)
    {
        try
        {
            interpreter.EventHandlers.OnTip(this, new TipEventArgs(context, (int)((double)arguments[0]), (string) arguments[1], (string) arguments[2]));
            return null;
        }
        catch (InvalidCastException)
        {
            throw new RuntimeError(null, $"tip() expects args:(int) (string) (string) .");
        }
    }
}

