////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
// 
////////////////////////////////////////

using BDSM.StandardLibrary;
using System;

#nullable disable

namespace BDSM.Events;

public class BDSMEventHandlers
{
    public EventHandler<DefineActorEventArgs> OnDefineActor = (_, __) => {};
    public EventHandler<DefineSceneEventArgs> OnDefineScene = (_, __) => {};
    public EventHandler<SetSceneEventArgs> OnSetScene = (_, __) => {};
    public EventHandler<SetPlayerEventArgs> OnSetPlayer = (_, __) => {};
    public EventHandler<ActorSayEventArgs> OnActorSay = (_, __) => {};
    public EventHandler<ActorTalkToEventArgs> OnActorTalkTo = (_, __) => {};
    public EventHandler<ItemPickupEventArgs> OnItemPickup = (_, __) => {};
    public EventHandler<PlayerItemRemoveEventArgs> OnPlayerItemRemove = (_, __) => {};
    public EventHandler<PlayerItemAddEventArgs> OnPlayerItemAdd = (_, __) => {};
    public EventHandler<ActorMoveEventArgs> OnActorMove = (_, __) => {};
    public EventHandler<SetPosEventArgs> OnSetPos = (_, __) => {};
    public EventHandler<ActorPutEventArgs> OnActorPut = (_, __) => {};
    public EventHandler<PlayAnimationEventArgs> OnPlayAnimation = (_, __) => {};
    public EventHandler<SceneAddEventArgs> OnSceneAdd = (_, __) => {};
    public EventHandler<SceneRemoveEventArgs> OnSceneRemove = (_, __) => {};
    public EventHandler<WaitEventArgs> OnWait = (_, __) => {};
    public EventHandler<ActorInterruptEventArgs> OnActorInterrupt = (_, __) => {};
    public EventHandler<CamZoomEventArgs> OnCamZoom = (_, __) => {};
    public EventHandler<SetCamPosEventArgs> OnSetCamPos = (_, __) => {};
    public EventHandler<CloseupEventArgs> OnCloseup = (_, __) => {};
    public EventHandler<PlaySongEventArgs> OnPlaySong = (_, __) => {};
    public EventHandler<PlaySoundEventArgs> OnPlaySound = (_, __) => {};
    public EventHandler<StopSongEventArgs> OnStopSong = (_, __) => {};
    public EventHandler<PlayVideoEventArgs> OnPlayVideo = (_, __) => {};
    public EventHandler<RequestMainMenuEventArgs> OnRequestMainMenu = (_, __) => {};
    public EventHandler<RequestTutorialEventArgs> OnRequestTutorial = (_, __) => {};
    public EventHandler<EndGameEventArgs> OnEndGame = (_, __) => {};
    public EventHandler<FadeInEventArgs> OnFadeIn = (_, __) => {};
    public EventHandler<FadeOutEventArgs> OnFadeOut = (_, __) => {};
    public EventHandler<CinematicStartEventArgs> OnCinematicStart = (_, __) => {};
    public EventHandler<CinematicEndEventArgs> OnCinematicEnd = (_, __) => {};
    public EventHandler<DetachCamEventArgs> OnDetachCam = (_, __) => {};
    public EventHandler<RequestStatePlayingEventArgs> OnRequestStatePlaying = (_, __) => {};
    public EventHandler<SetStateEventArgs> OnSetState = (_, __) => {};
    public EventHandler<InterruptEventArgs> OnInterrupt = (_, __) => {};
    public EventHandler<ActorSetIsShowChildrenEventArgs> OnActorSetIsShowChildren = (_, __) => {};
    public EventHandler<NarrateEventArgs> OnNarrate = (_, __) => {};
    public EventHandler<MoveCamToEventArgs> OnMoveCamTo = (_, __) => {};
    public EventHandler<SetCostumeEventArgs> OnSetCostume = (_, __) => {};
    public EventHandler<AutosaveEventArgs> OnAutosave = (_, __) => {};
    public EventHandler<FreespeechEventArgs> OnFreespeech = (_, __) => {};
    public EventHandler<RequestStartMenuEventArgs> OnRequestStartMenu = (_, __) => {};
    public EventHandler<TipEventArgs> OnTip = (_, __) => {};
    public EventHandler<NotifyEventArgs> OnNotify = (_, __) => {};
    public EventHandler<ClearInventoryEventArgs> OnClearInventory = (_, __) => {};

}

