//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.Actors;
using Beta.DI;
using Beta.Logging;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class ActorSetIsShowChildrenCommand : ActorCommand
{
    private readonly ILogger _logger;

    public bool IsShowChildren { get; set; }


    public ActorSetIsShowChildrenCommand(Actor actor, bool isShowChildren) : base(actor)
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();

        IsShowChildren = isShowChildren;
    }

    public override void Startup()
    {
        _logger.Debug();

        Actor.SetIsShowChildren(IsShowChildren);
        IsDone = true;
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    public override void OnComplete()
    {
        base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        _logger.Debug("");
    }

}