//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.AdditionalUi;
using Beta.DI;
using Beta.Logging;
using Beta.Services;
using Beta.Services.SaveGames;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class AutosaveCommand : Command
{
    private readonly ILogger _logger;
    private readonly SaveGameService _saveGameService;
    private readonly HistoryService _historyService;
    private readonly AdditionalUiManager _additionalUiManager;

    public AutosaveCommand()
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();

        _saveGameService = DependencyContainer.Instance.Get<SaveGameService>();

        _historyService = DependencyContainer.Instance.Get<HistoryService>();

        _additionalUiManager = DependencyContainer.Instance.Get<AdditionalUiManager>();
    }

    public override void Startup()
    {
        _logger.Debug();

        _saveGameService.AutosaveGame();

        _additionalUiManager.AutosaveSpinner.Start();

        IsDone = true;
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    private void AppendToHistory()
    {
        _historyService.Append("Game auto-saved.");
    }

    public override void OnComplete()
    {
        base.OnComplete();
        AppendToHistory();
        _additionalUiManager.AutosaveSpinner.Stop();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        AppendToHistory();
        _additionalUiManager.AutosaveSpinner.Stop();
        _logger.Debug("");
    }
}