//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.Common;
using Beta.DI;
using Beta.Logging;
using Beta.Phrases;
using Beta.Services;
using Beta.Services.Sounds;
using Beta.Text;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Graphics;
using MonoGame.Extended;
using System;
using System.Text.RegularExpressions;

namespace Beta.Commands;

public partial class FreespeechCommand : Command
{
    private readonly ILogger _logger;
    private readonly HistoryService _historyService;
    private readonly Phrase _phrase;
    private readonly Color _color;
    private readonly Vector2 _position;
    private readonly string[] _lines;
    private readonly ITextManager _textManager;
    private readonly PhraseSoundPlayer? _phrasePlayer;
    private EventHandler _onComplete = (_, _) => { };

    private float _timePassed;

    public FreespeechCommand(Phrase phrase, string actorName, Color color, Vector2 position)
    {
        SkipStyle = CommandSkipStyle.SkipOne;
        _phrase = phrase;
        _color = color;
        _position = position;
        _lines = _phrase.Text.Split('\n');
        _textManager = DependencyContainer.Instance.Get<ITextManager>();
        _logger = DependencyContainer.Instance.Get<ILogger>();
        _historyService = DependencyContainer.Instance.Get<HistoryService>();

        var contentCache = DependencyContainer.Instance.Get<ContentCache>();
        var sfx = contentCache.GetOrDefault<SoundEffect>($"sounds/actors/{actorName}.talk");
        if (sfx is not null)
        {
            _phrasePlayer = new(sfx, _phrase.Text);
        }
    }

    public override void Startup()
    {
        if (string.IsNullOrEmpty(_phrase.Text))
        {
            IsDone = true;
            return;
        }
    }

    public void Then(EventHandler then)
    {
        _onComplete += then;
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Trace("Update.");

        _timePassed += gameTime.GetElapsedSeconds();

        _phrasePlayer?.Update(gameTime);

        if (_timePassed >= _phrase.SecondsDuration)
        {
            IsDone = true;
        }

        return IsDone;
    }

    public override void Draw(SpriteBatch spriteBatch)
    {
        if (IsDone)
        {
            return;
        }

        var size = _textManager.GetLinesSize(_lines, TextManagerModule.Main);

        _textManager.WriteLines(
            spriteBatch,
            _lines,
            new TextWriteArgs
            {
                FontBinding = TextManagerModule.Main,
                Position = _position,
                Color = _color,
                TextAlignment = TextAlignment.Center,
                LayerDepth = Constants.LayerDepthSpeech,
            }
        );
    }

    private void AppendToHistory()
    {
        var text = NewLineRegex().Replace(_phrase.Text, "");
        _historyService.Append($"*{text}*");
    }

    public override void OnComplete()
    {
        base.OnComplete();
        AppendToHistory();
        _logger.Debug("");
        _onComplete(this, EventArgs.Empty);
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        AppendToHistory();
        _logger.Debug("");
        _onComplete(this, EventArgs.Empty);
    }

    [GeneratedRegex(@"\t|\n|\r")]
    private static partial Regex NewLineRegex();
}
