//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.CommandManagement;
using Beta.DI;
using Beta.Logging;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class InterruptCommand : Command
{
    private ILogger _logger;
    private readonly CommandManager _commandManager;

    private bool _interruptAsync;

    public InterruptCommand(bool interruptAsync)
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();
        _commandManager = DependencyContainer.Instance.Get<CommandManager>();
        _interruptAsync = interruptAsync;
    }

    public override void Startup()
    {
        _logger.Debug();

        _commandManager.Interrupt(_interruptAsync);
        IsDone = true;
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    public override void OnComplete()
    {
        base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        _logger.Debug("");
    }
}