//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.DI;
using Beta.Logging;
using Microsoft.Xna.Framework;
using MonoGame.Extended;

namespace Beta.Commands;

public class MoveCamToCommand : Command
{
    private ILogger _logger;
    private readonly OrthographicCamera _camera;

    public int X { get; set; }
    public int Y { get; set; }
    public int Speed { get; set; }

    public MoveCamToCommand(int x, int y, int speed)
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();
        _camera = DependencyContainer.Instance.Get<OrthographicCamera>();

        X = x;
        Y = y;
        Speed = speed;
    }

    public override void Startup()
    {
        _logger.Debug();
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();

        var vec = new Vector2(X - _camera.Position.X, Y - _camera.Position.Y);
        vec.Normalize();
        vec *= Speed;

        _camera.Position += vec;

        if ((_camera.Position - new Vector2(X, Y)).Length() < Speed)
        {
            IsDone = true;
        }

        return IsDone;
    }

    public override void OnComplete()
    {
		base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
		base.OnInterrupt();
        _logger.Debug("");
    }
}

