//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using System;
using System.Text.RegularExpressions;
using Beta.DI;
using Beta.Logging;
using Beta.Phrases;
using Beta.Services;
using Beta.Text;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using MonoGame.Extended;

namespace Beta.Commands;

public partial class NarrateCommand : Command
{
    private ILogger _logger;
    private Phrase _phrase;
    private string[] _lines;
    private readonly ITextManager _textManager;
    private readonly OrthographicCamera _camera;

    private readonly Color _backgroundColor;
    private readonly Color _narratorSpeechColor;
    private readonly HistoryService _historyService;
    private EventHandler _onComplete = (_, __) => { };

    private float _timePassed;

    public NarrateCommand(Phrase phrase)
    {
        SkipStyle = CommandSkipStyle.SkipOne;
        _phrase = phrase;
        _lines = _phrase.Text.Split('\n');
        _textManager = DependencyContainer.Instance.Get<ITextManager>();
        _logger = DependencyContainer.Instance.Get<ILogger>();
        _camera = DependencyContainer.Instance.Get<OrthographicCamera>();

        _backgroundColor = Constants.MainColor;
        _narratorSpeechColor = Constants.MainTextColor;

        _historyService = DependencyContainer.Instance.Get<HistoryService>();
    }

    public override void Startup()
    {
        _logger.Debug();

        if (string.IsNullOrEmpty(_phrase.Text))
        {
            IsDone = true;
            return;
        }
    }

    public void Then(EventHandler then)
    {
        _onComplete += then;
    }

    public override bool Update(GameTime gameTime)
    {
        _timePassed += gameTime.GetElapsedSeconds();

        if (_timePassed >= _phrase.SecondsDuration)
        {
            IsDone = true;
        }

        return IsDone;
    }

    public override void Draw(SpriteBatch spriteBatch)
    {
        if (IsDone)
        {
            return;
        }

        var rect = new RectangleF(
            _camera.BoundingRectangle.Left,
            _camera.BoundingRectangle.Bottom - 280f,
            _camera.BoundingRectangle.Width,
            250f
        );

        spriteBatch.FillRectangle(
            rect,
            _backgroundColor,
            layerDepth: Constants.LayerDepthFade + Constants.LayerDepthStep
        );

        var padding = 60f;
        _textManager.WriteLines(
            spriteBatch,
            _lines,
            new TextWriteArgs
            {
                FontBinding = TextManagerModule.Main,
                Position = new Vector2(rect.Center.X, rect.Top + padding),
                Color = _narratorSpeechColor,
                TextAlignment = TextAlignment.Center,
                LayerDepth = Constants.LayerDepthFade + (Constants.LayerDepthStep * 2),
            }
        );
    }

    private void AppendToHistory()
    {
        var text = NewLineRegex().Replace(_phrase.Text, "");
        _historyService.Append($"[{text}]");
    }

    public override void OnComplete()
    {
        base.OnComplete();
        AppendToHistory();
        _logger.Debug("");
        _onComplete(this, EventArgs.Empty);
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        AppendToHistory();
        _logger.Debug("");
        _onComplete(this, EventArgs.Empty);
    }

    [GeneratedRegex(@"\t|\n|\r")]
    private static partial Regex NewLineRegex();
}