//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.DI;
using Beta.Logging;
using Beta.Services;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class NotifyCommand : Command
{
    private readonly ILogger _logger;
    private readonly IToastService _toastService;

    public int DurationSeconds { get; set; }
    public string Text { get; set; }

    public NotifyCommand(int durationSeconds, string text)
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();
        _toastService = DependencyContainer.Instance.Get<IToastService>();
        DurationSeconds = durationSeconds;
        Text = text;
    }

    public override void Startup()
    {
        _toastService.Notify(DurationSeconds, Text);
        IsDone = true;
        _logger.Debug();
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    public override void OnComplete()
    {
        base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        _logger.Debug("");
    }
}