//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.AdditionalUi;
using Beta.DI;
using Beta.GameStates;
using Beta.Gui.Elements;
using Beta.Logging;
using Beta.Services.SaveGames;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class RequestStartMenuCommand : Command
{
    private readonly ILogger _logger;
    private readonly GameStateManager _gameStateManager;
    private readonly AdditionalUiManager _additionalUiManager;
    private readonly SaveGameService _saveGameService;

    public RequestStartMenuCommand()
    {
        _saveGameService = DependencyContainer.Instance.Get<SaveGameService>();
        _additionalUiManager = DependencyContainer.Instance.Get<AdditionalUiManager>();
        _gameStateManager = DependencyContainer.Instance.Get<GameStateManager>();
        _logger = DependencyContainer.Instance.Get<ILogger>();
    }

    public override void Startup()
    {
        _gameStateManager.RequestStateStartMenu();
        _additionalUiManager.LogoBanner.Start();

        // Yuk....
        var noAutosave = _saveGameService.FetchFromCache("autosave") is null;
        if (noAutosave)
        {
            Gui.Gui.Instance.TryFindById<TextButton>("start-continue-button", out var continueButton);
            continueButton?.SetDisabled(true);
        }

        IsDone = true;
        _logger.Debug();
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    public override void OnComplete()
    {
        base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        _logger.Debug("");
    }
}