//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.DI;
using Beta.GameStates;
using Beta.Logging;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class RequestStatePlayingCommand : Command
{
    private readonly ILogger _logger;
    private readonly GameStateManager _gameStateManager;

    public RequestStatePlayingCommand()
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();

        _gameStateManager = DependencyContainer.Instance.Get<GameStateManager>();
    }

    public override void Startup()
    {
        _logger.Debug();

        _gameStateManager.RequestStatePlaying();

        IsDone = true;
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    public override void OnComplete()
    {
        base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        _logger.Debug("");
    }
}