//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.Actors;
using Beta.DI;
using Beta.Logging;
using Microsoft.Xna.Framework;
using System;

namespace Beta.Commands;

public class SetStateCommand : ActorCommand
{
    private readonly ILogger _logger;

    public string State { get; set; }

    public SetStateCommand(Actor actor, string state) : base(actor)
    {
        _logger = DependencyContainer.Instance.Get<ILogger>();

        State = state;
    }

    public override void Startup()
    {
        _logger.Debug();

        if (ActorState.Idle.Name.Equals(State, StringComparison.OrdinalIgnoreCase))
        {
            Actor.ForceState(ActorState.Idle);
        }
        else
        {
            Actor.ForceState(new ActorState(State, isManuallyManaged: true));
        }

        IsDone = true;
    }

    public override bool Update(GameTime gameTime)
    {
        return IsDone;
    }

    public override void OnComplete()
    {
        base.OnComplete();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        _logger.Debug("");
    }
}