//////////////////////////////////////////////////////////////
//  
// NB: Auto-Generated by CommAdder Tool.
//      
// However, this file is meant to be modified according
// to the command needs. But take care NOT to regenerate it.
//
//////////////////////////////////////////////////////////////

using Beta.DI;
using Beta.Logging;
using Beta.Services;
using Microsoft.Xna.Framework;

namespace Beta.Commands;

public class TipCommand : Command
{
    private readonly ILogger _logger;
    private readonly IToastService _toastService;

    public int DurationSeconds { get; set; }
    public string Id { get; set; }
    public string Text { get; set; }
    private readonly HistoryService _historyService;

    private bool _wasShown;

    public TipCommand(int durationSeconds, string id, string text)
    {
        _historyService = DependencyContainer.Instance.Get<HistoryService>();
        _logger = DependencyContainer.Instance.Get<ILogger>();
        _toastService = DependencyContainer.Instance.Get<IToastService>();
        DurationSeconds = durationSeconds;
        Id = id;
        Text = text;
    }

    public override void Startup()
    {
        _logger.Debug();

        _wasShown = _toastService.ShowTip(DurationSeconds, Id, Text);

        IsDone = true;
    }

    public override bool Update(GameTime gameTime)
    {
        _logger.Debug();
        return IsDone;
    }

    private void AppendToHistory()
    {
        if (_wasShown)
        {
            _historyService.Append($"Tip: {Text}");
        }
    }

    public override void OnComplete()
    {
        base.OnComplete();
        AppendToHistory();
        _logger.Debug("");
    }

    public override void OnInterrupt()
    {
        base.OnInterrupt();
        AppendToHistory();
        _logger.Debug("");
    }
}