// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerSaveData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Beta.Services.SaveGames.SaveGameDatas {

  /// <summary>Holder for reflection information generated from PlayerSaveData.proto</summary>
  public static partial class PlayerSaveDataReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerSaveData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerSaveDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQbGF5ZXJTYXZlRGF0YS5wcm90bxIEQmV0YRoWVmVjdG9yMlN1cnJvZ2F0",
            "ZS5wcm90byJoCg5QbGF5ZXJTYXZlRGF0YRIUCgxjdXJyZW50U2NlbmUYASAB",
            "KAkSKAoIcG9zaXRpb24YAiABKAsyFi5CZXRhLlZlY3RvcjJTdXJyb2dhdGUS",
            "FgoOaW52ZW50b3J5SXRlbXMYAyADKAlCKKoCJUJldGEuU2VydmljZXMuU2F2",
            "ZUdhbWVzLlNhdmVHYW1lRGF0YXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Beta.Extensions.Models.Vector2SurrogateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData), global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData.Parser, new[]{ "CurrentScene", "Position", "InventoryItems" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerSaveData : pb::IMessage<PlayerSaveData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerSaveData> _parser = new pb::MessageParser<PlayerSaveData>(() => new PlayerSaveData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerSaveData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSaveData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSaveData(PlayerSaveData other) : this() {
      currentScene_ = other.currentScene_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      inventoryItems_ = other.inventoryItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSaveData Clone() {
      return new PlayerSaveData(this);
    }

    /// <summary>Field number for the "currentScene" field.</summary>
    public const int CurrentSceneFieldNumber = 1;
    private string currentScene_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurrentScene {
      get { return currentScene_; }
      set {
        currentScene_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::Beta.Extensions.Models.Vector2Surrogate position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Beta.Extensions.Models.Vector2Surrogate Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "inventoryItems" field.</summary>
    public const int InventoryItemsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_inventoryItems_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> inventoryItems_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> InventoryItems {
      get { return inventoryItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerSaveData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerSaveData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentScene != other.CurrentScene) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if(!inventoryItems_.Equals(other.inventoryItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentScene.Length != 0) hash ^= CurrentScene.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      hash ^= inventoryItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CurrentScene.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CurrentScene);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      inventoryItems_.WriteTo(output, _repeated_inventoryItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CurrentScene.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CurrentScene);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      inventoryItems_.WriteTo(ref output, _repeated_inventoryItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurrentScene.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentScene);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      size += inventoryItems_.CalculateSize(_repeated_inventoryItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerSaveData other) {
      if (other == null) {
        return;
      }
      if (other.CurrentScene.Length != 0) {
        CurrentScene = other.CurrentScene;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Beta.Extensions.Models.Vector2Surrogate();
        }
        Position.MergeFrom(other.Position);
      }
      inventoryItems_.Add(other.inventoryItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CurrentScene = input.ReadString();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::Beta.Extensions.Models.Vector2Surrogate();
            }
            input.ReadMessage(Position);
            break;
          }
          case 26: {
            inventoryItems_.AddEntriesFrom(input, _repeated_inventoryItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CurrentScene = input.ReadString();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::Beta.Extensions.Models.Vector2Surrogate();
            }
            input.ReadMessage(Position);
            break;
          }
          case 26: {
            inventoryItems_.AddEntriesFrom(ref input, _repeated_inventoryItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
