// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SaveGameData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Beta.Services.SaveGames.SaveGameDatas {

  /// <summary>Holder for reflection information generated from SaveGameData.proto</summary>
  public static partial class SaveGameDataReflection {

    #region Descriptor
    /// <summary>File descriptor for SaveGameData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SaveGameDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJTYXZlR2FtZURhdGEucHJvdG8SBEJldGEaE0ZpZWxkU2F2ZURhdGEucHJv",
            "dG8aE0FjdG9yU2F2ZURhdGEucHJvdG8aFFBsYXllclNhdmVEYXRhLnByb3Rv",
            "GhNTY2VuZVNhdmVEYXRhLnByb3RvIrcDCgxTYXZlR2FtZURhdGESLgoGc2Nl",
            "bmVzGAEgAygLMh4uQmV0YS5TYXZlR2FtZURhdGEuU2NlbmVzRW50cnkSLgoG",
            "YWN0b3JzGAIgAygLMh4uQmV0YS5TYXZlR2FtZURhdGEuQWN0b3JzRW50cnkS",
            "MAoHcGxheWVycxgDIAMoCzIfLkJldGEuU2F2ZUdhbWVEYXRhLlBsYXllcnNF",
            "bnRyeRIjCgZmaWVsZHMYBCABKAsyEy5CZXRhLkZpZWxkU2F2ZURhdGESDAoE",
            "dGltZRgFIAEoCRIUCgxjdXJyZW50U2NlbmUYBiABKAkaQgoLU2NlbmVzRW50",
            "cnkSCwoDa2V5GAEgASgJEiIKBXZhbHVlGAIgASgLMhMuQmV0YS5TY2VuZVNh",
            "dmVEYXRhOgI4ARpCCgtBY3RvcnNFbnRyeRILCgNrZXkYASABKAkSIgoFdmFs",
            "dWUYAiABKAsyEy5CZXRhLkFjdG9yU2F2ZURhdGE6AjgBGkQKDFBsYXllcnNF",
            "bnRyeRILCgNrZXkYASABKAkSIwoFdmFsdWUYAiABKAsyFC5CZXRhLlBsYXll",
            "clNhdmVEYXRhOgI4AUIoqgIlQmV0YS5TZXJ2aWNlcy5TYXZlR2FtZXMuU2F2",
            "ZUdhbWVEYXRhc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BDSM.Runtime.SaveGames.FieldSaveDataReflection.Descriptor, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveDataReflection.Descriptor, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveDataReflection.Descriptor, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Beta.Services.SaveGames.SaveGameDatas.SaveGameData), global::Beta.Services.SaveGames.SaveGameDatas.SaveGameData.Parser, new[]{ "Scenes", "Actors", "Players", "Fields", "Time", "CurrentScene" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SaveGameData : pb::IMessage<SaveGameData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SaveGameData> _parser = new pb::MessageParser<SaveGameData>(() => new SaveGameData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SaveGameData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Beta.Services.SaveGames.SaveGameDatas.SaveGameDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SaveGameData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SaveGameData(SaveGameData other) : this() {
      scenes_ = other.scenes_.Clone();
      actors_ = other.actors_.Clone();
      players_ = other.players_.Clone();
      fields_ = other.fields_ != null ? other.fields_.Clone() : null;
      time_ = other.time_;
      currentScene_ = other.currentScene_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SaveGameData Clone() {
      return new SaveGameData(this);
    }

    /// <summary>Field number for the "scenes" field.</summary>
    public const int ScenesFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveData>.Codec _map_scenes_codec
        = new pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveData.Parser), 10);
    private readonly pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveData> scenes_ = new pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.SceneSaveData> Scenes {
      get { return scenes_; }
    }

    /// <summary>Field number for the "actors" field.</summary>
    public const int ActorsFieldNumber = 2;
    private static readonly pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveData>.Codec _map_actors_codec
        = new pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveData.Parser), 18);
    private readonly pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveData> actors_ = new pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.ActorSaveData> Actors {
      get { return actors_; }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 3;
    private static readonly pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData>.Codec _map_players_codec
        = new pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData.Parser), 26);
    private readonly pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData> players_ = new pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Beta.Services.SaveGames.SaveGameDatas.PlayerSaveData> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "fields" field.</summary>
    public const int FieldsFieldNumber = 4;
    private global::BDSM.Runtime.SaveGames.FieldSaveData fields_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::BDSM.Runtime.SaveGames.FieldSaveData Fields {
      get { return fields_; }
      set {
        fields_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 5;
    private string time_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Time {
      get { return time_; }
      set {
        time_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currentScene" field.</summary>
    public const int CurrentSceneFieldNumber = 6;
    private string currentScene_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurrentScene {
      get { return currentScene_; }
      set {
        currentScene_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SaveGameData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SaveGameData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Scenes.Equals(other.Scenes)) return false;
      if (!Actors.Equals(other.Actors)) return false;
      if (!Players.Equals(other.Players)) return false;
      if (!object.Equals(Fields, other.Fields)) return false;
      if (Time != other.Time) return false;
      if (CurrentScene != other.CurrentScene) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Scenes.GetHashCode();
      hash ^= Actors.GetHashCode();
      hash ^= Players.GetHashCode();
      if (fields_ != null) hash ^= Fields.GetHashCode();
      if (Time.Length != 0) hash ^= Time.GetHashCode();
      if (CurrentScene.Length != 0) hash ^= CurrentScene.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      scenes_.WriteTo(output, _map_scenes_codec);
      actors_.WriteTo(output, _map_actors_codec);
      players_.WriteTo(output, _map_players_codec);
      if (fields_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Fields);
      }
      if (Time.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Time);
      }
      if (CurrentScene.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CurrentScene);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      scenes_.WriteTo(ref output, _map_scenes_codec);
      actors_.WriteTo(ref output, _map_actors_codec);
      players_.WriteTo(ref output, _map_players_codec);
      if (fields_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Fields);
      }
      if (Time.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Time);
      }
      if (CurrentScene.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CurrentScene);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += scenes_.CalculateSize(_map_scenes_codec);
      size += actors_.CalculateSize(_map_actors_codec);
      size += players_.CalculateSize(_map_players_codec);
      if (fields_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Fields);
      }
      if (Time.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Time);
      }
      if (CurrentScene.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentScene);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SaveGameData other) {
      if (other == null) {
        return;
      }
      scenes_.MergeFrom(other.scenes_);
      actors_.MergeFrom(other.actors_);
      players_.MergeFrom(other.players_);
      if (other.fields_ != null) {
        if (fields_ == null) {
          Fields = new global::BDSM.Runtime.SaveGames.FieldSaveData();
        }
        Fields.MergeFrom(other.Fields);
      }
      if (other.Time.Length != 0) {
        Time = other.Time;
      }
      if (other.CurrentScene.Length != 0) {
        CurrentScene = other.CurrentScene;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            scenes_.AddEntriesFrom(input, _map_scenes_codec);
            break;
          }
          case 18: {
            actors_.AddEntriesFrom(input, _map_actors_codec);
            break;
          }
          case 26: {
            players_.AddEntriesFrom(input, _map_players_codec);
            break;
          }
          case 34: {
            if (fields_ == null) {
              Fields = new global::BDSM.Runtime.SaveGames.FieldSaveData();
            }
            input.ReadMessage(Fields);
            break;
          }
          case 42: {
            Time = input.ReadString();
            break;
          }
          case 50: {
            CurrentScene = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            scenes_.AddEntriesFrom(ref input, _map_scenes_codec);
            break;
          }
          case 18: {
            actors_.AddEntriesFrom(ref input, _map_actors_codec);
            break;
          }
          case 26: {
            players_.AddEntriesFrom(ref input, _map_players_codec);
            break;
          }
          case 34: {
            if (fields_ == null) {
              Fields = new global::BDSM.Runtime.SaveGames.FieldSaveData();
            }
            input.ReadMessage(Fields);
            break;
          }
          case 42: {
            Time = input.ReadString();
            break;
          }
          case 50: {
            CurrentScene = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
